### ISSUE TITLE
Normalizing timestamps

### ISSUE THREAD

**Issue by junhyk** [HMEIatJHU/neural-hawkes-particle-smoothing#1]
Hi,

Just for curiosity,
does it make sense to somehow normalize timestamps or time intervals in this work?

**Comment by hongyuanmei** [comment]
> does it make sense to somehow normalize timestamps or time intervals in this work?

It surely does. 
Just review the log-likelihood with K=1: 
\sum_{i:t_i < T} \log \lambda(t_i) - \int_{t=0}^{T} \lambda(t) dt 

The integral term is approximately the expected # of event tokens in the sequence in (0,T], regardless of time unit. 
Then changing the unit of dt will affect the level of \lambda(t), thus affecting the magnitude of the sum term. 
You can normalize your time stamps to the level you feel comfortable with :-)
